# Generated by Django 5.1.15 on 2026-07-23 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=255)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('songs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Queue',
                'verbose_name_plural': 'Shared Queues',
                'ordering': ['-updated_at'],
            },
        ),
    ]
