# Generated by Django 5.1.15 on 2026-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='United States', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_artist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_genre',
            field=models.CharField(blank=True, default='Lo-Fi / R&B', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='listening_goal',
            field=models.CharField(blank=True, default='30 hrs / week', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
