# Generated by Django 5.1.15 on 2026-07-23 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=255)),
                ('current_song_id', models.CharField(default='song_1', max_length=255)),
                ('playback_state', models.CharField(choices=[('NO_SESSION', 'No Session'), ('SESSION_CREATED', 'Session Created'), ('WAITING_FOR_HOST', 'Waiting for Host'), ('READY', 'Ready'), ('PLAYING', 'Playing'), ('PAUSED', 'Paused'), ('SESSION_ENDED', 'Session Ended')], default='READY', max_length=50)),
                ('playback_position_ms', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_playback_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playback Session',
                'verbose_name_plural': 'Playback Sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
